import { SocketIndicator } from "@/components/socket-indicator";
import { QueryProvider } from "@/providers/query-provider";
import { SocketProvider } from "@/providers/socket-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>        
          <QueryProvider>     
          <SocketProvider>
          <SocketIndicator/> 
            {children}
          </SocketProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
